name: main

on:
  push:
    branches: [ v1.x, v2.x, v3.x ]
    tags:
    - '*'
  pull_request:
    branches: [ v1.x, v2.x, v3.x ]

jobs:
  codeberg:
    name: Codeberg
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 'Mirror to Codeberg'
      uses: yesolutions/mirror-action@master
      with:
        REMOTE: "https://codeberg.org/flowerinthenight/spindle.git"
        GIT_USERNAME: flowerinthenight
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}

  build:
    name: Build
    if: "!contains(github.event.commits[0].message, 'ci skip')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v6
      with:
        go-version: ^1.23

    - uses: actions/checkout@v6

    - name: 'Run tests'
      run: go test -v ./...
