name: main

on:
  push:
    branches: [ v1, v2, v3 ]
    tags:
    - '*'
  pull_request:
    branches: [ v1, v2, v3 ]

jobs:
  codeberg:
    name: Codeberg
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 'Mirror to Codeberg'
      uses: yesolutions/mirror-action@master
      with:
        REMOTE: "https://codeberg.org/flowerinthenight/spindle.git"
        GIT_USERNAME: flowerinthenight
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}

  build:
    name: Build
    if: "!contains(github.event.commits[0].message, 'ci skip')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v6
      with:
        go-version: ^1.23

    - uses: actions/checkout@v6

    - name: 'Start Spanner Emulator'
      run: |
        docker run -d -p 9010:9010 -p 9020:9020 gcr.io/cloud-spanner-emulator/emulator:latest
        
        # Wait for the emulator to be ready
        echo "Waiting for Spanner Emulator to start..."
        while ! nc -z localhost 9010; do
          sleep 1
        done
        echo "Spanner Emulator is up and running."

    - name: 'Run tests'
      run: go test -v ./...
      env:
        SPANNER_EMULATOR_HOST: localhost:9010
